const userCtrl = require('../controller/userController');
const author = require('./authorization');
const express = require('express');
const router = express.Router();
router.post('/login',userCtrl.login);
router.post('/register',userCtrl.register);
router.post('/forgotPassword',userCtrl.forgotPassword);
router.post('/resetPassword',userCtrl.resetPassword);
router.get('/getAllUser',userCtrl.getAllUser);
router.use('/auth',author);
module.exports = router;